#!/bin/sh

start() {
        printf "Starting alsa: "
        start-stop-daemon -S -x alsactl -- -b -e /var/run/alsa.pid -L rdaemon \
          && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping alsa: "
        start-stop-daemon -K --pidfile /var/run/alsa.pid \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac