#!/bin/sh

start() {
        printf "Starting radio: "
        start-stop-daemon --start -m --quiet --background --exec /root/radio.sh --pidfile /var/run/radio.pid \
                && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping radio: "
        start-stop-daemon --stop --quiet --pidfile /var/run/radio.pid \
                && echo "OK" || echo "FAIL"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart|reload)
                stop
                sleep 1
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac